<?xml version="1.0"?>
<package format="2">
  <name>f1tenth_racing</name>
  <version>0.0.1</version>
  <description>Pure Pursuit racing controller for F1TENTH</description>

  <maintainer email="student@example.com">Student</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  
  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>ackermann_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf</depend>

  <export>
  </export>
</package>